### ISSUE TITLE
pass module parameters from software

### ISSUE THREAD

**Issue by stresingbuero** [Entwicklungsburo-Stresing/EBST_CAM#58]
At the time it is only possible to use escam on linux with the compiled default parameters of the kernel object on module-main.h

DEFAULT_NUMBER_OF_CAMERAS
DEFAULT_NUMBER_OF_PIXELS

**Comment by gldhnchn** [comment]
It is. The DMA buffer is initialized when the kernel module is loaded. And for the size of the DMA buffer the pixel count is used. This is not a good system design, because in our software pixel count is a parameter that can be changed by the software, so it should not be fixed in the kernel module. Maybe a solution would be to move the DMA initialization to a different location.

**Comment by stresingbuero** [comment]
The maximum size of the dma buffer is now used at boot.
